# Generated by Django 4.0 on 2021-12-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category Id')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Product Id')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('desc', models.TextField(verbose_name='Product Description')),
                ('units', models.PositiveIntegerField(default=0, verbose_name='Product Units')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Product Category')),
            ],
        ),
    ]
